In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
df = pd.read_csv('D:/Sinau/Data Science Weekend/danthon2021/alerts.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7800662 entries, 0 to 7800661
Data columns (total 18 columns):
 #   Column                       Dtype  
---  ------                       -----  
 0   id                           int64  
 1   pub_millis                   int64  
 2   s2id_15                      int64  
 3   s2token_15                   object 
 4   road_type                    int64  
 5   street                       object 
 6   city                         object 
 7   magvar                       int64  
 8   reliability                  int64  
 9   report_description           float64
 10  report_rating                int64  
 11  confidence                   int64  
 12  type                         object 
 13  subtype                      object 
 14  report_by_municipality_user  float64
 15  n_thumbs_up                  float64
 16  longitude                    float64
 17  latitude                     float64
dtypes: float64(5), int64(8), object(5)
memory 

In [5]:
df.head().T

0                    1  \
id                                     177876895            179156987   
pub_millis                         1603331480000        1604487892000   
s2id_15                      3344466888162803712  3344463130066419712   
s2token_15                             2e69eeea4            2e69eb7f4   
road_type                                      1                    6   
street                                       NaN  N8 Jalan Raya Bogor   
city                                       Depok                Depok   
magvar                                         0                  170   
reliability                                    9                    7   
report_description                           NaN                  NaN   
report_rating                                  0                    1   
confidence                                     1                    1   
type                                 ROAD_CLOSED                  JAM   
subtype                        ROAD_CLOSED_EVENT    JAM_HEAVY_TRAFFIC   
report_by_municipality_user                  NaN                  NaN   
n_thumbs_up                                  NaN                  0.0   
longitude                             106.788545           106.867141   
latitude                               -6.359846            -6.383855   

                                               2                        3  \
id                                     181688703                173055165   
pub_millis                         1605666614000            1601895721000   
s2id_15                      3344367648648462336      3344374458319110144   
s2token_15                             2e6994a84                2e699ad9c   
road_type                                      7                        2   
street                                       NaN       Flyover Tegal Gede   
city                                      Bekasi                 Cikarang   
magvar                                         0                      319   
reliability                                    8                       10   
report_description                           NaN                      NaN   
report_rating                                  0                        5   
confidence                                     1                        0   
type                                 ROAD_CLOSED            WEATHERHAZARD   
subtype                        ROAD_CLOSED_EVENT  HAZARD_ON_ROAD_POT_HOLE   
report_by_municipality_user                  NaN                      NaN   
n_thumbs_up                                  NaN                      NaN   
longitude                             106.921974               107.143656   
latitude                               -6.379087                -6.300441   

                                               4  
id                                     173802602  
pub_millis                         1602464394000  
s2id_15                      3344466709921660928  
s2token_15                             2e69eec0c  
road_type                                      2  
street                           Tanjakan Kembar  
city                                       Depok  
magvar                                       310  
reliability                                    5  
report_description                           NaN  
report_rating                                  3  
confidence                                     0  
type                                         JAM  
subtype                        JAM_HEAVY_TRAFFIC  
report_by_municipality_user                  NaN  
n_thumbs_up                                  NaN  
longitude                              106.79395  
latitude                               -6.365677

In [6]:
df.isna().sum()

id                                   0
pub_millis                           0
s2id_15                              0
s2token_15                           0
road_type                            0
street                         1131669
city                                 0
magvar                               0
reliability                          0
report_description             7800662
report_rating                        0
confidence                           0
type                                 0
subtype                         196998
report_by_municipality_user    7800662
n_thumbs_up                    5285538
longitude                            0
latitude                             0
dtype: int64

In [7]:
df[df['id']==175242840]


id     pub_millis              s2id_15 s2token_15  road_type  \
1909252  175242840  1603029642000  3344175919160885248  2e68e647c          2   
3863713  175242840  1603029642000  3344175919160885248  2e68e647c          2   

              street     city  magvar  reliability  report_description  \
1909252  Purnawarman  Bandung       0            6                 NaN   
3863713  Purnawarman  Bandung       0            6                 NaN   

         report_rating  confidence         type            subtype  \
1909252              0           0  ROAD_CLOSED  ROAD_CLOSED_EVENT   
3863713              0           0  ROAD_CLOSED  ROAD_CLOSED_EVENT   

         report_by_municipality_user  n_thumbs_up   longitude  latitude  
1909252                          NaN          NaN  107.609332 -6.907551  
3863713                          NaN          NaN  107.609332 -6.907551

In [8]:
df.duplicated().sum()

1000000

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
len(df['street'].unique())

2145

In [11]:
df['city'].value_counts()

Bandung              3891363
Bekasi               1045831
Cikarang              671528
Depok                 376116
Bogor                 260984
Tambun Selatan         71751
Setu (Bekasi)          64196
Tambun Utara           62154
Cibitung (Bekasi)      58107
Babelan                57943
Parongpong             53146
Cileungsi              41040
Cibinong               28447
Cimahi                 28370
Tarumajaya             24832
Parung                 19401
Serang Baru            14657
Gunung Sindur          12166
Tangerang Selatan       9465
Gunung Putri            9165
Name: city, dtype: int64

In [12]:
len(df['magvar'].unique())

360

In [13]:
df['reliability'].value_counts()

6     3837304
5     1435304
10     771024
7      333695
8      238542
9      184793
Name: reliability, dtype: int64

In [14]:
df['report_description'].unique()

array([nan])

In [15]:
df['report_rating'].value_counts()

0    4163154
3     811759
2     603150
5     589237
1     372478
4     260884
Name: report_rating, dtype: int64

In [16]:
df['confidence'].value_counts()

0    5640205
1     513630
2     243531
3     153887
5     130154
4     119255
Name: confidence, dtype: int64

In [17]:
df['type'].value_counts()

ROAD_CLOSED      3722296
WEATHERHAZARD    1687483
JAM              1307455
ACCIDENT           83428
Name: type, dtype: int64

In [18]:
df['subtype'].value_counts()

ROAD_CLOSED_EVENT                     3721692
HAZARD_ON_ROAD_POT_HOLE               1377854
JAM_STAND_STILL_TRAFFIC                628687
JAM_HEAVY_TRAFFIC                      412979
HAZARD_ON_ROAD_CONSTRUCTION            178818
JAM_MODERATE_TRAFFIC                   157406
HAZARD_ON_SHOULDER_CAR_STOPPED          65202
HAZARD_ON_ROAD_CAR_STOPPED              23679
ACCIDENT_MAJOR                          22631
ACCIDENT_MINOR                          13415
HAZARD_WEATHER_FLOOD                     7481
HAZARD_ON_ROAD_OBJECT                    6894
HAZARD_ON_ROAD_ROAD_KILL                 2533
HAZARD_WEATHER_FOG                       1449
HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT       1393
HAZARD_ON_SHOULDER                       1029
HAZARD_WEATHER                           1018
HAZARD_ON_ROAD                           1001
HAZARD_WEATHER_HAIL                       940
HAZARD_ON_SHOULDER_MISSING_SIGN           800
HAZARD_ON_SHOULDER_ANIMALS                740
HAZARD_WEATHER_HEAVY_SNOW         

In [19]:
df['report_by_municipality_user'].unique()

array([nan])

In [20]:
df['n_thumbs_up'].unique()

array([nan,  0.])

In [21]:
df.drop(['report_by_municipality_user','n_thumbs_up','report_description','longitude','latitude','s2id_15','subtype'], axis=1, inplace=True)

In [22]:
df.head()

id     pub_millis s2token_15  road_type               street  \
0  177876895  1603331480000  2e69eeea4          1                  NaN   
1  179156987  1604487892000  2e69eb7f4          6  N8 Jalan Raya Bogor   
2  181688703  1605666614000  2e6994a84          7                  NaN   
3  173055165  1601895721000  2e699ad9c          2   Flyover Tegal Gede   
4  173802602  1602464394000  2e69eec0c          2      Tanjakan Kembar   

       city  magvar  reliability  report_rating  confidence           type  
0     Depok       0            9              0           1    ROAD_CLOSED  
1     Depok     170            7              1           1            JAM  
2    Bekasi       0            8              0           1    ROAD_CLOSED  
3  Cikarang     319           10              5           0  WEATHERHAZARD  
4     Depok     310            5              3           0            JAM

In [23]:
df.isna().sum()

id                    0
pub_millis            0
s2token_15            0
road_type             0
street           987122
city                  0
magvar                0
reliability           0
report_rating         0
confidence            0
type                  0
dtype: int64

In [24]:
df.dropna(axis=0, inplace=True)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5813540 entries, 1 to 7800661
Data columns (total 11 columns):
 #   Column         Dtype 
---  ------         ----- 
 0   id             int64 
 1   pub_millis     int64 
 2   s2token_15     object
 3   road_type      int64 
 4   street         object
 5   city           object
 6   magvar         int64 
 7   reliability    int64 
 8   report_rating  int64 
 9   confidence     int64 
 10  type           object
dtypes: int64(7), object(4)
memory usage: 532.2+ MB


In [26]:
df.to_csv('alerts_pre.csv', index=False)